-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- xcursor settings

hl.env("XCURSOR_SIZE", 24)

hl.env("XCURSOR_THEME", "breeze_cursors")

-- hyprcursor settings

hl.env("HYPRCURSOR_SIZE", 24)
