-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- XDG Desktop Portal

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- QT

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "kde")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1,")

-- GTK

hl.env("GDK_SCALE", 1)

hl.env("GTK_THEME", "Adwaita-dark")

-- Mozilla

hl.env("MOZ_ENABLE_WAYLAND", 1)

-- OZONE

hl.env("OZONE_PLATFORM", "wayland")
