-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- https://wiki.hyprland.org/Configuring/Monitors/

-- uncomment lines as needed for monitors

--monitor=eDP-1,preferred,auto,1

hl.monitor({
    output   = "DP-1",
    mode     = "1920x1080@144",
    position = "auto",
    scale    = 1,
})
